WORKDIR=/home/richard/Documents/Professional/INRIA-ATOS-BULL/These-gitlab/llvm_pass
PERSODIR=/home/richard/Documents/MyProjects/RUST/UNFINISHED/calendar
UNITYDIR=/home/richard/Documents/MyProjects/UNITY/godWork
alias cdu="cd $UNITYDIR"
alias cdd="cd ~/Downloads"
export LIBS_DIR=/home/richard/Documents/Libraries
export HWLOC_HOME=${LIBS_DIR}/hwloc-2.4.1/install
export LLVM_HOME=${LIBS_DIR}/llvm-15/install
export MPI_HOME=${LIBS_DIR}/openmpi-4.1.4/install
export PGMATH_HOME=${LIBS_DIR}/libpgmath/install
export RUST_HOME=${LIBS_DIR}/rust
export RUSTUP_HOME=${RUST_HOME}
export CARGO_HOME=${RUST_HOME}
export GO_HOME=${LIBS_DIR}/go-1.17.3
export GOPATH=/home/richard/Documents/MyProjects/GO
alias mk="$LIBS_DIR/man_perso.sh"
