WORKDIR=~/Documents/Professional/INRIA-ATOS-BULL/These-gitlab/llvm_pass
#PERSODIR=~/Documents/MyProjects/RUST
PERSODIR=~/Documents/MyProjects/PYTHON/AI_images
UNITYDIR=~/Documents/MyProjects/UNITY/godWork
alias cdu="cd $UNITYDIR"
alias cdd="cd ~/Downloads"
export LIBS_DIR=/home/richard/Documents/Libraries
export HWLOC_HOME=${LIBS_DIR}/hwloc/install
export LLVM_HOME=${LIBS_DIR}/llvm/install
export MPI_HOME=${LIBS_DIR}/openmpi/install
export CMAKE_HOME=${LIBS_DIR}/cmake/install
export RUSTUP_HOME=${LIBS_DIR}/rust/rustup
export CARGO_HOME=${LIBS_DIR}/rust/cargo
alias mk="$LIBS_DIR/man_perso.sh"
