export PROXY=host.containers.internal:9000
WORKDIR=~/THESIS-gitlab
SHARED_FOLDER=/mnt/c/SHARED_FOLDER
alias cds="cd $SHARED_FOLDER"
export LIBS_DIR=/home/rsartori/LIBS
export LLVM_HOME=${LIBS_DIR}/llvm/install
export HWLOC_HOME=${LIBS_DIR}/hwloc/install
export MPI_HOME=${LIBS_DIR}/mpi/install
export CMAKE_HOME=${LIBS_DIR}/cmake/install
export RUSTUP_HOME=${LIBS_DIR}/rust/rustup
export CARGO_HOME=${LIBS_DIR}/rust/cargo
alias evince="wslview"
export _INKSCAPE_GC=disable # inkscape fix
export PYTHON_HOME=/home/rsartori/.local
